import { useRef, useState } from 'react'
import './PersonalPortfolio.css'

const github = 'https://github.com/ronaelmoura'
const desk = 'https://ronas-desk.onrender.com/'
const linkedin = 'https://www.linkedin.com/in/ronael-moura'
const topics = [
  { name: 'Arquitetura', title: 'Cada camada tem uma responsabilidade.', text: 'React cuida da experiência. A API REST organiza as regras de negócio. MySQL mantém os dados relacionais. Essa separação permite evoluir a interface sem espalhar regras críticas pelo cliente.', items: ['React · interface', 'Node.js + Express · regras', 'MySQL · persistência'] },
  { name: 'Segurança', title: 'Acesso certo, para a pessoa certa.', text: 'Autenticação JWT, permissões por perfil, Helmet e limite de tentativas no login protegem os fluxos. A demonstração usa uma conta somente leitura e dados fictícios.', items: ['JWT e perfis de acesso', 'Rate limit no login', 'Anexos privados'] },
  { name: 'Testes', title: 'Confiança construída a cada entrega.', text: 'O Ronas Desk reúne 316 testes automatizados no backend. A evolução em 19 sprints conecta validação de regras, histórico de mudanças e entrega incremental.', items: ['Node Test Runner', '316 testes no backend', '19 sprints de evolução'] },
  { name: 'Deploy', title: 'O trabalho continua depois do commit.', text: 'A aplicação é conteinerizada e publicada no Render. O banco MySQL usa TLS no Aiven; os anexos ficam no Cloudinary. Migrações versionadas acompanham a evolução do produto.', items: ['Docker + Nginx', 'Render + Aiven', 'Cloudinary'] },
]
const projects = [
  { name: 'Nexo', type: 'INTERFACE & DADOS', desc: 'Dados financeiros que fazem sentido.', text: 'Dashboard financeiro com gráficos interativos, filtros por período, transações e temas claro e escuro.', tags: ['React', 'TypeScript', 'Recharts'], url: 'https://ronaelmoura.github.io/nexo-dashboard-financeiro/', repo: 'nexo-dashboard-financeiro', style: 'nexo', mark: 'N', detail: 'FINANÇAS, EM PERSPECTIVA' },
  { name: 'StockFlow API', type: 'BACK-END & NEGÓCIO', desc: 'Estoque e pedidos na mesma página.', text: 'API com autenticação, controle de movimentações e validações de negócio para manter a operação consistente.', tags: ['Node.js', 'Express', 'MySQL'], repo: 'stockflow-api', style: 'stock', mark: '{ }', detail: 'REGRAS QUE SUSTENTAM A OPERAÇÃO' },
  { name: 'ClimaZen', type: 'EXPERIÊNCIA & CONVERSÃO', desc: 'Do primeiro acesso ao orçamento.', text: 'Site para uma empresa fictícia de climatização, com simulador de economia e formulário interativo.', tags: ['React', 'UX/UI', 'Responsivo'], url: 'https://ronaelmoura.github.io/climazen-landing-page/', repo: 'climazen-landing-page', style: 'clima', mark: 'C°', detail: 'CONFORTO INTELIGENTE' },
  { name: 'Ronas Tech', type: 'TECNOLOGIA & NEGÓCIO', desc: 'Pequenos negócios. Novas possibilidades.', text: 'Sites, sistemas e automações apresentados com identidade própria e um caminho direto para iniciar uma conversa.', tags: ['React', 'Produto', 'SEO'], url: 'https://www.ronastech.com.br/', repo: 'ronas-tech-site', style: 'ronas', mark: 'RT', detail: 'TECNOLOGIA COM PROPÓSITO' },
]
function Arrow() { return <span aria-hidden="true">↗</span> }
function External({ href, children, className = '' }) { return <a className={className} href={href} target="_blank" rel="noreferrer">{children}<Arrow /></a> }
export default function PersonalPortfolio() {
  const [menu, setMenu] = useState(false)
  const [topic, setTopic] = useState(0)
  const dialog = useRef(null)
  const active = topics[topic]
  return <div className="folio">
    <a className="skip-link" href="#conteudo">Pular para o conteúdo</a>
    <header className="pf-header"><a className="pf-brand" href="#inicio">rm<span>.</span></a><nav aria-label="Navegação principal" className={menu ? 'pf-nav open' : 'pf-nav'}>{[['projetos', 'Projetos'], ['sobre', 'Sobre'], ['stack', 'Stack'], ['contato', 'Contato']].map(([id, label]) => <a key={id} href={'#' + id} onClick={() => setMenu(false)}>{label}</a>)}</nav><button className="pf-recruiter" onClick={() => dialog.current.showModal()}>Modo recrutador <Arrow /></button><button className="pf-menu" aria-label={menu ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menu} onClick={() => setMenu(!menu)}>{menu ? 'Fechar' : 'Menu'}</button></header>
    <main id="conteudo">
      <section className="pf-hero pf-wrap" id="inicio">
        <div className="pf-hero-top"><span className="pf-kicker">RONAEL MOURA / DESENVOLVEDOR FULL STACK</span><span className="pf-available"><i /> Disponível para oportunidades</span></div>
        <div className="pf-hero-grid"><div className="pf-intro"><h1>Do problema<br />ao produto.<br /><em>De ponta<br className="pf-mobile-break" /> a ponta.</em></h1><p>Construo aplicações com <strong>React e Node.js</strong>, unindo o olhar de quem entende o usuário à engenharia de quem entrega a solução.</p><div className="pf-actions"><a className="pf-button" href="#projetos">Explore meu trabalho <Arrow /></a><External className="pf-text-link" href={github}>GitHub</External></div></div><div className="pf-portrait"><span className="pf-photo-index">01 / QUEM CONSTRÓI</span><img src="/ronael-moura.webp" alt="Ronael Moura, desenvolvedor Full Stack" width="1100" height="1100" fetchPriority="high" /><div className="pf-photo-caption"><span>Ronael Moura<small>Do suporte de TI ao software.</small></span><span className="pf-photo-arrow" aria-hidden="true">↗</span></div></div></div>
        <div className="pf-hero-bottom"><span>ENTENDER. CONSTRUIR. VALIDAR. ENTREGAR.</span><a href="#projetos">Veja na prática <span aria-hidden="true">↓</span></a></div>
      </section>
      <section className="pf-work pf-wrap" id="projetos"><div className="pf-section-heading"><div><span className="pf-kicker">01 / TRABALHO SELECIONADO</span><h2>Menos promessa.<br /><em>Mais produto.</em></h2></div><p>Projetos que conectam interface, regras de negócio e uma boa experiência para quem usa.</p></div>
        <article className="pf-feature" id="ronas-desk"><div className="pf-feature-copy"><span className="pf-label"><i /> PROJETO PRINCIPAL · V1.0</span><h3>Ronas Desk<span>Suporte organizado.<br />Operação sob controle.</span></h3><p>Da experiência no suporte de TI nasceu uma plataforma Full Stack para centralizar chamados, clientes, equipe, SLA e indicadores.</p><div className="pf-tags"><span>React</span><span>Node.js</span><span>MySQL</span><span>Docker</span></div><div className="pf-actions"><External className="pf-button" href={desk}>Explorar demonstração</External><External className="pf-text-link" href={github + '/ronas-desk'}>Ver código</External></div></div><div className="pf-system"><div className="pf-system-top"><span>RD<span className="pf-dot">.</span></span><span>RONAS DESK / ENGENHARIA</span><span className="pf-live">v1.0</span></div><div className="pf-system-title"><span>DA INTERFACE À INFRAESTRUTURA</span><h4>Um produto.<br />Todas as camadas.</h4></div><div className="pf-layers">{[['01', 'Experiência', 'React · portal do cliente'], ['02', 'Regras & acesso', 'API REST · JWT · SLA'], ['03', 'Dados & entrega', 'MySQL · Docker · Render']].map(([n, t, d]) => <div key={n}><span>{n}</span><strong>{t}<small>{d}</small></strong><span aria-hidden="true">↗</span></div>)}</div><div className="pf-system-foot">ARQUITETURA DO PROJETO <span>↓</span></div></div><div className="pf-evidence"><div><strong>316<span> testes</span></strong><small>automatizados no backend</small></div><div><strong>19<span> sprints</span></strong><small>de evolução do produto</small></div><div><strong>v1.0<span> online</span></strong><small>da arquitetura ao deploy</small></div></div></article>
        <div className="pf-projects">{projects.map((p, i) => <article key={p.name} className={'pf-project ' + p.style}><div className="pf-project-cover"><span>0{i + 2} / {p.type}</span><strong>{p.mark}</strong><span>{p.detail}<Arrow /></span></div><div className="pf-project-copy"><h3>{p.name}</h3><h4>{p.desc}</h4><p>{p.text}</p><div className="pf-tags">{p.tags.map(t => <span key={t}>{t}</span>)}</div><div className="pf-project-links">{p.url && <External href={p.url}>Ver projeto</External>}<External href={github + '/' + p.repo}>Código e detalhes</External></div></div></article>)}</div>
      </section>
      <section className="pf-engineering pf-wrap" id="stack"><div className="pf-section-heading"><div><span className="pf-kicker">02 / POR TRÁS DA ENTREGA</span><h2>O código resolve.<br /><em>As decisões sustentam.</em></h2></div><p>Um olhar sobre as escolhas técnicas do Ronas Desk, com evidências abertas no GitHub.</p></div><div className="pf-tech-panel"><div className="pf-tabs" role="tablist" aria-label="Decisões técnicas">{topics.map((t, i) => <button key={t.name} role="tab" id={'tab-' + i} aria-selected={topic === i} aria-controls="tech-content" tabIndex={topic === i ? 0 : -1} onClick={() => setTopic(i)} onKeyDown={e => { if (['ArrowRight','ArrowLeft','Home','End'].includes(e.key)) { e.preventDefault(); const next = e.key === 'Home' ? 0 : e.key === 'End' ? 3 : (i + (e.key === 'ArrowRight' ? 1 : 3)) % 4; setTopic(next); document.getElementById('tab-' + next).focus() } }}><span>0{i + 1}</span>{t.name}<span aria-hidden="true">↗</span></button>)}</div><div role="tabpanel" id="tech-content" aria-labelledby={'tab-' + topic} className="pf-tech-content"><span className="pf-kicker">RONAS DESK / {active.name.toUpperCase()}</span><h3>{active.title}</h3><p>{active.text}</p><div className="pf-tags">{active.items.map(t => <span key={t}>{t}</span>)}</div><External className="pf-text-link" href={github + '/ronas-desk'}>Investigar no código</External></div></div><div className="pf-stack-line"><span>MINHA STACK</span><p>React <b>/</b> Node.js <b>/</b> Express <b>/</b> MySQL <b>/</b> Docker <b>/</b> Git</p></div></section>
      <section className="pf-about pf-wrap" id="sobre"><div><span className="pf-kicker">03 / QUEM ESTÁ POR TRÁS</span><h2>Antes de escrever código,<br /><em>aprendi a ouvir.</em></h2><div className="pf-about-copy"><p>Comecei no suporte de TI, investigando problemas e ajudando pessoas a seguir com o trabalho. Essa experiência continua no meu jeito de desenvolver: entender primeiro, construir com propósito.</p><p>Hoje conecto interfaces, APIs, bancos de dados e deploy para transformar problemas operacionais em produtos web. Na Ronas Tech, aplico esse conhecimento em soluções para pequenos negócios.</p><External className="pf-text-link" href={linkedin}>Conheça minha trajetória</External></div></div><div className="pf-journey" id="jornada">{[['01', 'A base', 'Suporte em TI', 'Escuta, investigação e responsabilidade pela solução.'], ['02', 'A formação · 2025', 'Full Stack no SENAI', '670 horas · SENAI Piauí · conceito APTO.'], ['03', 'A prática', 'Produto em produção', 'Projetos públicos, aprendizado compartilhado e Ronas Desk v1.0.']].map(([n,k,t,d]) => <article key={n}><span>{n}</span><div><small>{k}</small><h3>{t}</h3><p>{d}</p></div></article>)}</div></section>
      <section className="pf-contact" id="contato"><div className="pf-wrap"><span className="pf-kicker">04 / PRÓXIMA CONVERSA</span><div className="pf-contact-heading"><h2>Seu próximo desafio.<br /><em>Minha próxima entrega.</em></h2><a className="pf-contact-arrow" href="mailto:ronaelmoura240@gmail.com" aria-label="Enviar e-mail para Ronael Moura">↗</a></div><div className="pf-contact-bottom"><p>Aberto a oportunidades Full Stack,<br />colaborações e projetos com propósito.</p><a href="mailto:ronaelmoura240@gmail.com">ronaelmoura240@gmail.com ↗</a></div></div></section>
    </main><footer className="pf-footer pf-wrap"><a className="pf-brand" href="#inicio">rm<span>.</span></a><span>© {new Date().getFullYear()} Ronael Moura</span><div><External href={github}>GitHub</External><External href={linkedin}>LinkedIn</External><External href="/curriculo-ronael-moura.pdf">Currículo</External></div><a href="#inicio">Voltar ao topo ↑</a></footer>
    <dialog ref={dialog} className="pf-dialog" onClick={e => { if (e.target === e.currentTarget) dialog.current.close() }}><div className="pf-dialog-head"><span className="pf-kicker">RESUMO PROFISSIONAL</span><button aria-label="Fechar resumo" onClick={() => dialog.current.close()}>✕</button></div><h2>Ronael Moura<span>Desenvolvedor Full Stack</span></h2><p>React, Node.js, Express e MySQL. Experiência em suporte de TI e formação Full Stack no SENAI Piauí, com 670 horas.</p><h3>Evidência em produção</h3><p>Ronas Desk v1.0: plataforma de Help Desk com 316 testes no backend, autenticação, permissões, SLA, portal do cliente e deploy conteinerizado.</p><div className="pf-actions"><External className="pf-button" href="/curriculo-ronael-moura.pdf">Abrir currículo</External><External className="pf-text-link" href={desk}>Ver Ronas Desk</External></div><a className="pf-dialog-email" href="mailto:ronaelmoura240@gmail.com">ronaelmoura240@gmail.com ↗</a></dialog>
  </div>
}

